pipeline {
    agent any

    environment {
        registry = 'amits64'
        repository = 'my-webapp'
        registryCredential = 'dockerhub'
        tag = "v${BUILD_NUMBER}"
    }

    stages {
        stage('git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Amits64/khut-project.git'
                dir('project-1') {
                }
            }
        }
        
        stage('Build docker image') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${registry}/${repository}:${tag}", "-f project-1/Dockerfile .")
                }
            }
        }

        stage('Upload Image') {
            steps {
                script {
                    // Push the Docker image to the registry
                    docker.withRegistry('', registryCredential) {
                        docker.image("${registry}/${repository}:${tag}").push()
                    }
                }
            }
        }

        stage('Remove Unused docker image') {
            steps {
                script {
                    sh "docker rmi ${registry}/${repository}:${tag}"
                }
            }
        }

        stage('Deploying container to Kubernetes') {
            steps {
                script {
                    sh "helm install my-webapp project-1 --set appimage=${registry}/${repository}:${tag}"
                }
            }
        }
    }
}
