pipeline {
    agent any

    environment {
        registry = 'amits64'
        repository = 'my-webapp'
        registryCredential = 'dockerhub'
        tag = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/Amits64/khut-project.git']]
                ])
                dir('project-1') {
                    // Define your Git-related operations here if needed
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${registry}/${repository}:${tag}", "-f project-1/Dockerfile .")
                }
            }
        }

        stage('Upload Image') {
            steps {
                script {
                    // Push the Docker image to the registry
                    docker.withRegistry('', registryCredential) {
                        docker.image("${registry}/${repository}:${tag}").push()
                    }
                }
            }
        }

        stage('Remove Unused Docker Image') {
            steps {
                script {
                    sh "docker rmi ${registry}/${repository}:${tag}"
                }
            }
        }

        stage('Deploying Container to Kubernetes') {
            steps {
                dir('project-1/my-webapp') {
                    // Install Helm chart (chart directory is specified here)
                    sh "helm install my-webapp ./ -n my-webapp --set appimage=amits64/my-webapp:${tag} --set-file ca.crt=/etc/ca-certificates/update.d/jks-keystore"
                }
            }
        }
    }
}
